version: 2

sources:
  - name: bjj
    schema: bjj
    tables:
      - name: class_attendance
      - name: positions_practiced
      - name: moves_practiced
      - name: position
      - name: move
      - name: class
