dbt_bjj:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('BJJ_DB_HOST') }}"
      user: "{{ env_var('BJJ_DB_USER') }}"
      pass: "{{ env_var('BJJ_DB_PWD') }}"
      port: "{{ env_var('BJJ_DB_PORT') | int }}"
      dbname: "{{ env_var('BJJ_DB_DATABASE') }}"
      schema: bjj

    prod:
      type: postgres
      threads: 4
      host: "{{ env_var('BJJ_DB_HOST') }}"
      user: "{{ env_var('BJJ_DB_USER') }}"
      pass: "{{ env_var('BJJ_DB_PWD') }}"
      port: "{{ env_var('BJJ_DB_PORT', 5432) | int }}"
      dbname: "{{ env_var('BJJ_DB_DATABASE') }}"
      schema: bjj

  target: dev
